#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_task_status:
    path: /api/tasks/{id}/status
    methods: [PUT]
    controller: App\Controller\TodolistController::updateStatus